### ISSUE TITLE
Teleport message for operators not working

### ISSUE THREAD

**Issue by Sikatsu** [jolbol1/RandomCoordinatesV2#5]
When I use /rtp as operator, no message that says ''You will be teleported in 5 seconds!'' appears.

When I do it with my alt account, it works.

**Comment by jolbol1** [comment]
Operators should have the bypass permission, This means they bypass both the cooldown and time before teleporting, so I believe this is correct. Will look into it though.

**Comment by Sikatsu** [comment]
Well, either the bypass is not working correctly or it's teleporting isn't instant. I have to wait before being teleported but no message shows up.

**Comment by jolbol1** [comment]
What options do you have enabled for safe checking? E.g., Factions and things. As an OP you should be teleporting right away so If you're not, it means the plugin is doing some checking.

**Comment by Sikatsu** [comment]
As an operator I just have to wait for the timer, just without the message.
I have worldborder and worldguard set to true.

Op ma 13 mrt. 2017 21:44 schreef jolbol1 <notifications@github.com>:

**Comment by jolbol1** [comment]
This is another headscratcher, As a /OP you get every permission so that included the bypass time before one. On my servers I'm bypassing it as an OP.

**Comment by jolbol1** [comment]
Closing this as I believe it should now be fixed in the upcoming version. If it is not then I will look into it further, as the code seems correct.

**Comment by Sikatsu** [comment]
Alright, I will inform you if the issue still occurs on my side.

**Comment by Sikatsu** [comment]
If you want to, you can come and see it on my server. This still occurs on the latest version.

**Comment by jolbol1** [comment]
Are you sure the delay is the same as the TimeBefore? The only way I can recreate this is when WorldGuard check is on its a slow process on their end, Thus there is a small delay between the command and teleporting. 

While I'd love to come on the server and see for myself, the WiFi that I'm currently on weirdly blocks almost every server I can only access Hive and Hypixel. What's the IP? I could give it a go, But doubtful it would let me :(

**Comment by Sikatsu** [comment]
The IP is mc.villagercraft.eu / 	89.163.206.130. Give it a try.

Config: http://pastebin.com/Rfk4HcPD

I just used /rtp as an operator. I counted and after 5 seconds I was teleported. The config says 2 seconds, though.

**Comment by jolbol1** [comment]
Yeah, this is what I thought it would be. For some reason the function to get the regions at a specific location when hooking into the WorldGuard plugin is very slow, thus causes a delay while it is checking. 

I will look into improving this but it doesn't appear to be my code that is slow.

**Comment by Sikatsu** [comment]
If it takes 5 seconds for an operator and for a normal player just the 2 seconds I've set, isn't that completely weird? :P

**Comment by jolbol1** [comment]
For a regular player is there no delay whatsoever after the 2 seconds? If so then yes I'm completely confused.

**Comment by Sikatsu** [comment]
Oh wait, no it's actually 5 seconds. Also on my alternative account. But then still the bypass isn't working. And the delay option becomes pretty useless.

**Comment by jolbol1** [comment]
Im going to guess that for whatever reason the WorldGuard check is taking 5 seconds. I'm going to look into improving this but it could take a lot of time, The WG plugin seems oddly slow.

**Comment by Sikatsu** [comment]
Most if not all randomtp plugins are instant even with worldguard I though. It's not a big issue and it can wait, though.

**Comment by jolbol1** [comment]
This would be instant if not for the Radius check around the location they teleport too.

**Comment by jolbol1** [comment]
This brought to light quite a serious bug. If the CheckingRadius is to high, The command will not work and could cause a crash. 

I have been working on new methods to do this all day, and am happy to say it is fixed in the upcoming version. 

Here is an example with a checking radius of 1000 while WorldGuard is installed.
![alt text](https://media.giphy.com/media/GomOykXR0VCNO/giphy.gif "Logo Title Text 1")https://media.giphy.com/media/GomOykXR0VCNO/giphy.gif

**Comment by Sikatsu** [comment]
Interesting, but the CheckingRadius is set to 100 within my config. Which is the default CheckingRadius, yet it still takes atleast 5 seconds to be teleported.

**Comment by jolbol1** [comment]
Not sure I made that clear clear :P  This is the new v0.2.0 update where I fixed it. (I hope)
